CREATE TABLE MARCA (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DATA_INSERT TIMESTAMP NOT NULL,
    DATA_UPDATE TIMESTAMP NOT NULL
);

INSERT INTO MARCA(NOME, DATA_INSERT, DATA_UPDATE) VALUES ('FIAT', now(), now());
INSERT INTO MARCA(NOME, DATA_INSERT, DATA_UPDATE) VALUES ('FORD', now(), now());
INSERT INTO MARCA(NOME, DATA_INSERT, DATA_UPDATE) VALUES ('NISSAN', now(), now());
INSERT INTO MARCA(NOME, DATA_INSERT, DATA_UPDATE) VALUES ('TOYOTA', now(), now());
INSERT INTO MARCA(NOME, DATA_INSERT, DATA_UPDATE) VALUES ('CHEVLOLET', now(), now());
