CREATE TABLE MODELO (
    ID SERIAL PRIMARY KEY,
    MARCA_ID INTEGER NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    DATA_INSERT TIMESTAMP NOT NULL,
    DATA_UPDATE TIMESTAMP NOT NULL,
    FOREIGN KEY (MARCA_ID) REFERENCES MARCA (ID)
);

INSERT INTO MODELO(MARCA_ID, NOME, DATA_INSERT, DATA_UPDATE) VALUES (1, 'UNO', now(), now());
INSERT INTO MODELO(MARCA_ID, NOME, DATA_INSERT, DATA_UPDATE) VALUES (1, 'DUCATO', now(), now());

INSERT INTO MODELO(MARCA_ID, NOME, DATA_INSERT, DATA_UPDATE) VALUES (2, 'BELINA', now(), now());
INSERT INTO MODELO(MARCA_ID, NOME, DATA_INSERT, DATA_UPDATE) VALUES (2, 'ECOSPORT', now(), now());
INSERT INTO MODELO(MARCA_ID, NOME, DATA_INSERT, DATA_UPDATE) VALUES (2, 'DEL REY', now(), now());

INSERT INTO MODELO(MARCA_ID, NOME, DATA_INSERT, DATA_UPDATE) VALUES (4, 'COROLLA', now(), now());
