CREATE TABLE VERSAO (
    ID SERIAL PRIMARY KEY,
    MODELO_ID INTEGER NOT NULL,
    DESCRICAO VARCHAR(150) NOT NULL,
    DATA_INSERT TIMESTAMP NOT NULL,
    DATA_UPDATE TIMESTAMP NOT NULL,
    FOREIGN KEY (MODELO_ID) REFERENCES MODELO (ID)
);

INSERT INTO VERSAO(MODELO_ID, DESCRICAO, DATA_INSERT, DATA_UPDATE) VALUES (1, '1.0 MPI MILLE FIRE 8V FLEX 2P MANUAL', now(), now());
INSERT INTO VERSAO(MODELO_ID, DESCRICAO, DATA_INSERT, DATA_UPDATE) VALUES (1, '1.0 MPI MILLE FIRE 8V FLEX 4P MANUAL', now(), now());
INSERT INTO VERSAO(MODELO_ID, DESCRICAO, DATA_INSERT, DATA_UPDATE) VALUES (1, '1.0 MPI MILLE FIRE 8V GASOLINA 2P MANUAL', now(), now());

INSERT INTO VERSAO(MODELO_ID, DESCRICAO, DATA_INSERT, DATA_UPDATE) VALUES (6, '1.6 GLI 16V GASOLINA 4P MANUAL', now(), now());
INSERT INTO VERSAO(MODELO_ID, DESCRICAO, DATA_INSERT, DATA_UPDATE) VALUES (6, '1.6 GLI 16V GASOLINA 4P AUTOMÁTICO', now(), now());
